### PR TITLE
Updated CAIHP, added translations, requests, basic portal, help page.

### PR DESCRIPTION
**Pull request by lcapkovic**
[Review on Reviewable](https://reviewable.io/reviews/sosik/registries-data-caihp/12)

### CODE REVIEW

**Comment by sosik** [comment]
lukas, unacceptable commit messages, sorry, you have to reword

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12)

**Comment by sosik** [comment]
Reviewed 25 of 34 files at r1.
Review status: 25 of 34 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[js/x-translations.js, line 809 \[r1\]](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12#-Js1ygf_F2_KZzdxWnzd)** ([raw file](https://github.com/sosik/registries-data-caihp/blob/d4300c47469323f8c1bcbdc45aaef302e2dc4c62/js/x-translations.js#L809)):</sup>
As in another review, shouldn't this be part of core?

---

<sup>**[partials/createMember.html, line 6 \[r1\]](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12#-Js1ywz2FOG_b-Y0_Yn-)** ([raw file](https://github.com/sosik/registries-data-caihp/blob/d4300c47469323f8c1bcbdc45aaef302e2dc4c62/partials/createMember.html#L6)):</sup>
This is really nasty html fragment. It is definitely not correct as you define HTML tag inside partial/fragment and continue directly with DIV.
And to be honest i do not understand to meaning of this partial as it is completely empty.
Please check it.

---

<sup>**[portal/client/css/font-awesome.min.css, line 1 \[r1\]](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12#-Js1zYyLDI0Yi-n4kTuA)** ([raw file](https://github.com/sosik/registries-data-caihp/blob/d4300c47469323f8c1bcbdc45aaef302e2dc4c62/portal/client/css/font-awesome.min.css#L1)):</sup>
This file should not be there. this is not ok i think as font-awesome is downloaded by bower and it should be never commited as direct dependency.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12)

**Comment by sosik** [comment]
Review status: 25 of 34 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[portal/client/css/font-awesome.min.css, line 1 \[r1\]](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12#-Js1zYyLDI0Yi-n4kTuA)** ([raw file](https://github.com/sosik/registries-data-caihp/blob/d4300c47469323f8c1bcbdc45aaef302e2dc4c62/portal/client/css/font-awesome.min.css#L1)):</sup>
Same apply to all following font-awesome files

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12)

**Comment by lcapkovic** [comment]
<sup>**[partials/createMember.html, line 6 \[r1\]](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12#-Js1ywz2FOG_b-Y0_Yn-)** ([raw file](https://github.com/sosik/registries-data-caihp/blob/d4300c47469323f8c1bcbdc45aaef302e2dc4c62/partials/createMember.html#L6)):</sup>
I just copied this from SZH as a part of making requests work, the create member button in peopleRegistrationSolver didn't work without it. I'll look into it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12)

**Comment by sosik** [comment]
css/custom.css is still loaded in index.html it cannot be deleted
don't forget to update user rights
font awesome problem

---

Reviewed 2 of 34 files at r1, 10 of 20 files at r2.
Review status: 30 of 40 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12)

**Comment by sosik** [comment]
Reviewed 6 of 20 files at r2, 22 of 31 files at r3.
Review status: 41 of 50 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[css/custom.css, line 16 \[r3\]](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12#-JsjAzutDeIt8Mb_cZEh)** ([raw file](https://github.com/sosik/registries-data-caihp/blob/8c4491455a07679dd91bcc7325f52065c13749c3/css/custom.css#L16)):</sup>
pff :D asi nie vsak

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sosik/registries-data-caihp/12)

**Pull request merged**
